server:
  port: 8087

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          # El Auth no lleva filtro, es la puerta de entrada libre

        - id: commerce-service
          uri: http://commerce-service:8082
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter # ðŸ‘ˆ Â¡Filtro activado!

        - id: user-service
          uri: http://user-service:8086
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter # ðŸ‘ˆ Â¡Filtro activado!

        - id: catalog-service
          uri: http://catalog-service:8084
          predicates:
            - Path=/api/courses/**, /api/admin/**
          filters:
            - AuthenticationFilter # ðŸ‘ˆ Â¡Filtro activado!

app:
  jwt:
    public-key: classpath:public_key.pem
