server:
  port: 8087

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
        - id: commerce-service
          uri: http://commerce-service:8082
          predicates:
            - Path=/api/payment/**
        - id: user-service
          uri: http://user-service:8086
          predicates:
            - Path=/api/users/**
        - id: catalog-service
          uri: http://catalog-service:8084
          predicates:
            - Path=/api/courses/**, /api/admin/**
